export const background = '#FFFFFF'

export const black = 'rgba(0, 0, 0, 1)'
export const white = 'white'
export const grey = '#6D7986'
export const lightGrey = '#B0B6BE'
export const red = 'rgba(228, 5, 57, 1)'
export const yellow = '#facd02'
export const blue = '#2980B9'
export const button = '#facd02'
export const backroundPrimary = '#FFFFFF'
export const backroundSecondary = '#F2F3F3'
export const input = '#F8F8F8;'
export const orange = 'orange'
export const gold = '#FFD700'
export const lgold = '#F0E68C'
