export const ROOT_MAIN = 'rootMain'

// SCREENS
export const SCREEN_HOME = 'HomeScreen'
export const SCREEN_LOGIN = 'LoginScreen'
export const SCREEN_USER_LOGIN = 'UserLoginScreen'
export const SCREEN_E_LOGIN = 'ELoginScreen'
export const SCREEN_FOOD_DETAIL = 'FoodDetail'
export const SCREEN_POPULAR = 'Popular'
export const SCREEN_SALAD = 'Salad'
export const SCREEN_BREAKFAST = 'Breakfast'
export const SCREEN_FIRST_SCREEN = 'FirstScreen'
export const SCREEN_CART_SCREEN = 'CartScreen'
export const SCREEN_TABLERES = 'TableResScreen'
export const SCREEN_BROADCAST = 'BroadCastScreen'
export const SCREEN_CONTACT = 'ContactScreen'
